#!/bin/bash

ULA_MAIN_MODULE="ula.sv"
AND_8_BITS_TESTBENCH="tests/and_8_bits_testbench.sv"
OR_8_BITS_TESTBENCH="tests/or_8_bits_testbench.sv"
SUBTRACTOR_BIT_TESTBENCH="tests/subtractor_1_bit_testbench.sv"
SUBTRACTOR_8_BITS_TESTBENCH="tests/subtractor_8_bits_testbench.sv"
NOT_8_BITS_TESTBENCH="tests/not_8_bits_testbench.sv"

# And 8 bits
echo "========================================================"
echo "Running and 8 bits testbench."
echo "========================================================"

PROJECT_NAME="and_8_bits"

iverilog -o $PROJECT_NAME $ULA_MAIN_MODULE $AND_8_BITS_TESTBENCH

vvp $PROJECT_NAME

echo "Runned and 8 bits testbench."


# Or 8 bits
echo "========================================================"
echo "Running or 8 bits testbench."
echo "========================================================"
PROJECT_NAME="or_8_bits"

iverilog -o $PROJECT_NAME $ULA_MAIN_MODULE $OR_8_BITS_TESTBENCH

vvp $PROJECT_NAME

echo "Runned or 8 bits testbench."

# Subtractor 1 bit
echo "========================================================"
echo "Running subtractor 1 bit testbench."
echo "========================================================"

PROJECT_NAME="subtractor_1_bit"

iverilog -o $PROJECT_NAME $ULA_MAIN_MODULE $SUBTRACTOR_BIT_TESTBENCH

vvp $PROJECT_NAME

echo "Runned subtractor 1 bit testbench."

# Subtractor 8 bit
echo "========================================================"
echo "Running subtractor 8 bits testbench."
echo "========================================================"

PROJECT_NAME="subtractor_8_bits"

iverilog -o $PROJECT_NAME $ULA_MAIN_MODULE $SUBTRACTOR_8_BITS_TESTBENCH

vvp $PROJECT_NAME

echo "Runned subtractor 8 bits testbench."

# Not 8 bits
echo "========================================================"
echo "Running not 8 bits testbench."
echo "========================================================"
PROJECT_NAME="not_8_bits"

iverilog -o $PROJECT_NAME $ULA_MAIN_MODULE $NOT_8_BITS_TESTBENCH

vvp $PROJECT_NAME

echo "Runned not 8 bits testbench."

echo "Success! Script has finished running."